name: Erlang CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - "24"
          - "23"
          - "22"
    container:
      image: erlang:${{ matrix.otp }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: git config --global --add safe.directory /__w/riak_repl_pb_api/riak_repl_pb_api/ && make
      - name: Run tests
        run: make check
